const GITHUB_TOKEN = process.env.GITHUB_TOKEN!
const NEXT_PUBLIC_GITHUB_USERNAME = process.env.NEXT_PUBLIC_GITHUB_USERNAME!
const NEXT_PUBLIC_DOMAIN = process.env.NEXT_PUBLIC_DOMAIN!
export {GITHUB_TOKEN, NEXT_PUBLIC_GITHUB_USERNAME, NEXT_PUBLIC_DOMAIN}