const GITHUB_TOKEN = process.env.GITHUB_TOKEN!
const GITHUB_USERNAME = process.env.GITHUB_USERNAME!
const NEXT_PUBLIC_DOMAIN = process.env.NEXT_PUBLIC_DOMAIN!
export {GITHUB_TOKEN, GITHUB_USERNAME, NEXT_PUBLIC_DOMAIN}